### ISSUE TITLE
What functions will recipe-generator have?  List them here.

### ISSUE THREAD

**Issue by WebshockInnovations** [WebshockInnovations/recipe-generator#1]

**Comment by WebshockInnovations** [comment]
Test

**Comment by WebshockJennifer** [comment]
Measurements metric system conversion for all users e.g. lbs vs grams.
Portions most people have a difficult time cooking for 2 people or less.
The majority of recipes have serving size 4-6 people we have to gear ideas
to budget, breaking down recipes so that the portion fits the needs of the
number of people that it will feed e.g.  smaller scale vs larger scale.

**Comment by WebshockInnovations** [comment]
https://docs.google.com/spreadsheets/d/1SGGLzeFpqDFEd2XNL5SlkEdiXR72_1SjBhYvOEpeuI0/edit?usp=sharing
